### ISSUE TITLE
Set security rule for the branch.

### ISSUE THREAD

**Issue by Yisaer** [Yisaer/benchmark-operator#2]
Set security rule for the branch in this repo.

**Comment by Yisaer** [comment]
The pull request shouldn't  be merged with at least 2 approved.

**Comment by Yisaer** [comment]
The `master` branch shouldn't be pushed directly.

**Comment by zhoudian64** [comment]
Only repo admin can set security rule in "Settings>Branches".

> The `master` branch shouldn't be pushed directly.

and this rule seems not available now.(https://help.github.com/en/github/administering-a-repository/enabling-branch-restrictions)

**Comment by Yisaer** [comment]
> Only repo admin can set security rule in "Settings>Branches".
> 
> > The `master` branch shouldn't be pushed directly.
> 
> and this rule seems not available now.(https://help.github.com/en/github/administering-a-repository/enabling-branch-restrictions)

Cool, I will try it myself.
